config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'cv', to: 'pages#cv'

  # Add CRUDs
  resources :skills, only: :index

  # Add CRUDs (for rich text management) after core pages are complete
  resources :projects, only: :index
  resources :projects, param: :title, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :authenticate_user!, raise: false

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @skills = Skill.all
    @projects = Project.all
  end

  def about
  end

  def cv
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find_by(title: params[:title])
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alec Strobel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <%# Navbar %>
    <% unless current_page?(cv_path) %>
      <%= render "components/navbar" %>
    <% end %>

    <%# Flash Alerts %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%# Floating Bars %>
    <% unless current_page?(cv_path) %>
      <%= render "components/floating_sidebar" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="mx-6 container relative md:pt-14">

  <div class="w-full lg:flex md:gap-4 lg:mt-10">
    <div class="order-2 flex flex-col w-full mb-24 lg:w-2/4 lg:flex-row justify-center items-center lg:mt-4">
      <%= image_tag 'portrait-2', class: "rounded-full w-[300px] h-[300px] md:w-[400px] md:h-[400px]" %>
    </div>
    <div class="order-1 lg:w-2/4 lg:pl-3">
      <h1 class="font-bold mb-5">Hi 👋 I'm Alec</h1>
      <h4 class="leading-7">I’m a problem solver at heart. Always have been. I’ve always been fascinated by technology and the endless possibilities it offers. The dream of creating innovative tech products that solve real-world problems is what drives me every day. I currently specialise in product design and software development, but my passion extends to the entire process of building digital products. My goal is now to continue further down the software development path. I am constantly seeking opportunities to enhance my skills and knowledge in this field and to bring my creative vision to life through the products I develop.</h4>
    </div>
  </div>

</div>

app/views/pages/cv.html.erb
<embed type="application/pdf" src="<%= asset_path('pdf/resume.pdf') %>" class="w-screen h-screen">

app/views/pages/home.html.erb
<div class="mx-6 container 2xl:max-w-screen-2xl relative">

  <%# Hero Section %>
  <div class="w-full lg:h-screen flex justify-center mb-28 mt-32 lg:mb-0 lg:mt-0 lg:items-center">
    <div class="mt-8">
      <h1 class="font-bold text-3xl leading-10 sm:leading-[4rem] sm:text-4xl lg:leading-[4rem] lg:text-5xl mb-5 xl:mb-6">Hi 👋 I'm a creative problem solver with a passion for creating tech products.</h1>
      <%= link_to "Check out my resume →", cv_path, class: "click-me hover:opacity-75", target: "_blank" %>
    </div>
  </div>

  <%# Intro Section %>
  <div class="mb-32">

    <div class="flex flex-col md:flex-row gap-4">
      <div class="flex items-center justify-center w-full sm:w-2/4 md:w-1/3">
        <%= image_tag "portrait.png", class: "rounded-3xl" %>
      </div>
      <div class="flex flex-col w-11/12 sm:w-2/4 md:w-2/3 pl-3 md:pl-5 lg:pl-10 justify-center items-center">
        <div>
          <h3 class="mt-4 md:mt-3 mb-4 xl:my-8">I'm a software developer with a background in design. I have experience in designing and developing end-to-end web app and native app products. My dream is to improve the lives of others through elegant solutions that solve real challenges of both people and businesses.</h3>
          <%= link_to "More about me →", about_path, class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

  </div>

  <%# Skill List %>
  <div class="mb-16 md:mb-32 lg:mb-36">

    <ul class="list-none flex flex-col md:flex-row items-center justify-between" data-controller="skills">
      <li class="flex justify-center items-center md:p-4 h-28 md:h-60 w-72" data-action="mouseover->skills#showCircleOne">
        <h2 class="text-[22px] leading-6 flex flex-row md:flex-col lg:flex-row"><span class="flex justify-center">Software</span>&nbsp;<span class="flex justify-center">Developer</span></h2>
      </li>
      <li class="flex justify-center items-center md:p-4 h-28 md:h-60 w-72" data-action="mouseover->skills#showCircleTwo">
        <h2 class="text-[22px] leading-6 flex flex-row md:flex-col lg:flex-row"><span class="flex justify-center">Problem</span>&nbsp;<span class="flex justify-center">Solver</span></h2>
      </li>
      <li class="flex justify-center items-center md:p-4 h-28 md:h-60 w-72" data-action="mouseover->skills#showCircleThree">
        <h2 class="text-[22px] leading-6 flex flex-row md:flex-col lg:flex-row"><span class="flex justify-center">Product</span>&nbsp;<span class="flex justify-center">Designer</span></h2>
      </li>
    </ul>
  </div>

  <%# Project Section %>
  <div class="mb-44">

    <div class="lg:flex lg:gap-4 mb-20 lg:mb-32">
      <div class="flex flex-col lg:flex-row items-center justify-center w-full lg:w-2/4">
        <%= link_to project_path(@projects[0].title) do %>
          <%= image_tag @projects[0].thumbnail, class: "rounded-3xl" %>
        <% end %>
      </div>
      <div class="flex flex-col w-full pl-5 lg:w-2/4 lg:pl-10 justify-center items-center">
        <div>
          <h2 class="mt-8 mb-4"><%= @projects[0].sub_title %></h2>
          <%= link_to "Read more →", project_path(@projects[0].title), class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

    <div class="lg:flex lg:gap-4 mb-20 lg:mb-32">
      <div class="order-2 flex flex-col lg:flex-row items-center justify-center w-full lg:w-2/4">
        <%= link_to project_path(@projects[1].title) do %>
          <%= image_tag @projects[1].thumbnail, class: "rounded-3xl" %>
        <% end %>
      </div>
      <div class="flex flex-col order-1 w-full pl-5 lg:w-2/4 lg:pl-10 justify-center items-center">
        <div>
          <h2 class="mt-8 mb-4"><%= @projects[1].sub_title %></h2>
          <%= link_to "Read more →", project_path(@projects[1].title), class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

    <div class="lg:flex lg:gap-4 mb-20 lg:mb-32">
      <div class="flex flex-col lg:flex-row items-center justify-center w-full lg:w-2/4">
        <%= link_to @projects[2].title do %>
          <%= image_tag @projects[2].thumbnail, class: "rounded-3xl" %>
        <% end %>
      </div>
      <div class="flex flex-col w-full pl-5 lg:w-2/4 lg:pl-10 justify-center items-center">
        <div>
          <h2 class="mt-8 mb-4"><%= @projects[2].sub_title %></h2>
          <%= link_to "Read more →", project_path(@projects[2].title), class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

    <div class="lg:flex lg:gap-4 mb-20 lg:mb-32">
      <div class="order-2 flex flex-col lg:flex-row items-center justify-center w-full lg:w-2/4">
        <%= link_to @projects[3].title do %>
          <%= image_tag @projects[3].thumbnail, class: "rounded-3xl" %>
        <% end %>
      </div>
      <div class="flex flex-col order-1 w-full pl-5 lg:w-2/4 lg:pl-10 justify-center items-center">
        <div>
          <h2 class="mt-8 mb-4"><%= @projects[3].sub_title %></h2>
          <%= link_to "Read more →", project_path(@projects[3].title), class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

    <div class="lg:flex lg:gap-4 mb-20 lg:mb-32">
      <div class="flex flex-col lg:flex-row items-center justify-center w-full lg:w-2/4">
        <%= link_to @projects[4].title do %>
          <%= image_tag @projects[4].thumbnail, class: "rounded-3xl" %>
        <% end %>
      </div>
      <div class="flex flex-col w-full pl-5 lg:w-2/4 lg:pl-10 justify-center items-center">
        <div>
          <h2 class="mt-8 mb-4"><%= @projects[4].sub_title %></h2>
          <%= link_to "Read more →", project_path(@projects[4].title), class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

  </div>

  <%# Quote Section %>
  <div class="mb-32">

    <div>
      <h1 class="mb-3">“The best way to predict the future is to create it.”</h1>
      <h3>- Alan Klay</h3>
    </div>

  </div>

  <%# About Section %>
  <div class="mb-48">

    <div class="md:flex md:gap-4">
      <div class="order-2 flex items-center justify-center w-full md:w-1/3">
        <%= image_tag "lines/donuts.svg", class: "rounded-3xl" %>
      </div>
      <div class="flex flex-col order-1 w-full md:w-2/3 md:pr-10 justify-center items-center">
        <div>
          <h3 class="mt-8 mb-5">I'm aspiring to become a great developer with Ruby and Javascript as my foundation, but I'm eager to expand my skillset. I'm fascinated by the intersection of design and technology and how they can be used to solve meaningful challenges.</h3>
          <%= link_to "Skills overview →", skills_path, class: "click-me hover:opacity-75" %>
        </div>
      </div>

    </div>

  </div>

  <%# Contact Section %>
  <div class="mb-32">

    <div class="contact-request">
      <h2 class="mb-5">Get in touch if you're interested in working with me! I'd love to meet over a call.</h2>
      <a href="mailto: contact@alecstrobel.tech" class="click-me hover:opacity-75">Get in touch →</a>
    </div>

  </div>

</div>

app/views/projects/index.html.erb
<div class="mx-6 container relative pt-14">

  <%# Project Section %>
  <div class="lg:mb-44">

    <div class="lg:flex lg:gap-4 mb-20 lg:mb-32">
      <div class="flex flex-col lg:flex-row items-center justify-center w-full lg:w-2/4">
        <%= link_to project_path(@projects[0].title) do %>
          <%= image_tag @projects[0].thumbnail, class: "rounded-3xl" %>
        <% end %>
      </div>
      <div class="flex flex-col w-full pl-5 lg:w-2/4 lg:pl-10 justify-center items-center">
        <div>
          <h2 class="mt-8 mb-4"><%= @projects[0].sub_title %></h2>
          <%= link_to "Read more →", project_path(@projects[0].title), class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

    <div class="lg:flex lg:gap-4 mb-20 lg:mb-32">
      <div class="order-2 flex flex-col lg:flex-row items-center justify-center w-full lg:w-2/4">
        <%= link_to project_path(@projects[1].title) do %>
          <%= image_tag @projects[1].thumbnail, class: "rounded-3xl" %>
        <% end %>
      </div>
      <div class="flex flex-col order-1 w-full pl-5 lg:w-2/4 lg:pl-10 justify-center items-center">
        <div>
          <h2 class="mt-8 mb-4"><%= @projects[1].sub_title %></h2>
          <%= link_to "Read more →", project_path(@projects[1].title), class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

    <div class="lg:flex lg:gap-4 mb-20 lg:mb-32">
      <div class="flex flex-col lg:flex-row items-center justify-center w-full lg:w-2/4">
        <%= link_to @projects[2].title do %>
          <%= image_tag @projects[2].thumbnail, class: "rounded-3xl" %>
        <% end %>
      </div>
      <div class="flex flex-col w-full pl-5 lg:w-2/4 lg:pl-10 justify-center items-center">
        <div>
          <h2 class="mt-8 mb-4"><%= @projects[2].sub_title %></h2>
          <%= link_to "Read more →", project_path(@projects[2].title), class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

    <div class="lg:flex lg:gap-4 mb-20 lg:mb-32">
      <div class="order-2 flex flex-col lg:flex-row items-center justify-center w-full lg:w-2/4">
        <%= link_to @projects[3].title do %>
          <%= image_tag @projects[3].thumbnail, class: "rounded-3xl" %>
        <% end %>
      </div>
      <div class="flex flex-col order-1 w-full pl-5 lg:w-2/4 lg:pl-10 justify-center items-center">
        <div>
          <h2 class="mt-8 mb-4"><%= @projects[3].sub_title %></h2>
          <%= link_to "Read more →", project_path(@projects[3].title), class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

    <div class="lg:flex lg:gap-4 mb-20 lg:mb-32">
      <div class="flex flex-col lg:flex-row items-center justify-center w-full lg:w-2/4">
        <%= link_to @projects[4].title do %>
          <%= image_tag @projects[4].thumbnail, class: "rounded-3xl" %>
        <% end %>
      </div>
      <div class="flex flex-col w-full pl-5 lg:w-2/4 lg:pl-10 justify-center items-center">
        <div>
          <h2 class="mt-8 mb-4"><%= @projects[4].sub_title %></h2>
          <%= link_to "Read more →", project_path(@projects[4].title), class: "click-me hover:opacity-75" %>
        </div>
      </div>
    </div>

  </div>

  <%# Contact Section %>
  <div class="mb-24">

    <div class="contact-request">
      <h2 class="mb-5">Get in touch if you're interested in working with me! I'd love to meet over a call.</h2>
      <a href="#" class="click-me hover:opacity-75">Get in touch →</a>
    </div>

  </div>

</div>

app/views/projects/show.html.erb
<div class="mx-6 container relative md:pt-14">

  <%# Header %>
  <div class="w-full flex flex-col lg:flex-row">
    <div class="order-2 w-full lg:w-2/4 flex justify-center">
      <%= image_tag @project.images[0], class: "rounded-3xl max-h-[500px]	" %>
    </div>
    <div class="order-1 w-full lg:w-2/4 lg:pt-24 xl:pt-32 lg:pl-3">
      <h1 class="text-5xl sm:text-7xl font-bold mb-5"><%= @project.title %></h1>
      <h2 class="text-2xl md:text-3xl leading-10 lg:mb-6"><%= @project.sub_title %></h2>
    </div>
  </div>

  <%# Project Details %>
  <div class="mb-6">
    <label for="accordion-1">
      <input type="checkbox" id="accordion-1" class="peer hidden">
      <div class="flex gap-6">
        <h2 class="text-xl mb-5">Project Role / Skills</h2>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="2.5"
          stroke="currentColor"
          class="mt-1 h-6 w-6">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
        </svg>
      </div>
      <div class="hidden peer-checked:grid peer-checked:grid-cols-1 sm:peer-checked:grid-cols-2 md:peer-checked:grid-cols-4 peer-checked:gap-4">
        <% @project.details.each do |detail| %>
          <div class="p-2 flex justify-center items-center w-full h-20 border-solid border-2 border-gray-800 rounded-lg hover:border-indigo-600 hover:border-4"><h3 class="text-center text-lg"><%= detail %></h3></div>
        <% end %>
      </div>
    </label>
  </div>

  <div class="mb-20">
    <label for="accordion-2">
      <input type="checkbox" id="accordion-2" class="peer hidden">
      <div class="flex gap-6">
        <h2 class="text-xl mb-5">Languages & Tools</h2>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="2.5"
          stroke="currentColor"
          class="mt-1 h-6 w-6">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
        </svg>
      </div>
      <div class="hidden peer-checked:grid peer-checked:grid-cols-2 sm:peer-checked:grid-cols-3 lg:peer-checked:grid-cols-4 peer-checked:gap-4">
        <% @project.tools.each do |tool| %>
          <div class="p-2 flex justify-center items-center w-full h-20 border-solid border-2 border-gray-800 rounded-lg hover:border-indigo-600 hover:border-4"><h3 class="text-center text-lg"><%= tool %></h3></div>
        <% end %>
      </div>
    </label>
  </div>

  <%# Sections %>
  <div class="mt-10 mb-5 ">
    <h2 class="mb-3">Overview</h2>
    <h4 class="text-xl leading-8"><%= @project.content[0] %></h4>
  </div>

  <div>
    <div class="flex flex-col md:flex-row gap-4">
      <div class="flex items-center justify-center w-full md:w-2/4">
        <%= image_tag @project.images[1], class: "rounded-3xl max-h-[500px]	" %>
      </div>
      <div class="flex items-center justify-center w-full md:w-2/4">
        <%= image_tag @project.images[2], class: "rounded-3xl max-h-[500px]	" %>
      </div>
    </div>
  </div>

  <div>
    <h2 class="mb-3">Outcome</h2>
    <h4 class="text-xl leading-8"><%= @project.content[1] %></h4>
    <% if @project.link.present? %>
      <h4 class="text-xl mt-8"><%= link_to "Check out the project here →", @project.link, class: "click-me hover:opacity-75" %></h4>
    <% end %>
  </div>

  <div class="my-12 lg:my-20">
    <div class="flex flex-col lg:flex-row gap-4">
      <div class="flex items-center justify-center w-full lg:w-2/4">
        <%= image_tag @project.images[3], class: "rounded-3xl max-h-[500px]	" %>
      </div>
      <div class="w-full lg:w-2/4">
        <h2 class="lg:mt-16 mb-5">Key Take Aways</h2>
        <h4 class="text-xl leading-8"><%= @project.content[2] %></h4>
      </div>
    </div>
  </div>

</div>

app/views/skills/index.html.erb
<div class="container relative pt-14">

  <div class="mb-28">
    <div class="mb-14">
      <h1 class="mb-5">Software Development</h1>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <% @skills[0].topics.each do |topic| %>
          <div class="p-2 flex justify-center items-center w-full h-20 border-solid border-2 border-gray-800 rounded-lg hover:border-indigo-600 hover:border-4"><h3 class="text-lg text-center"><%= topic %></h3></div>
        <% end %>
      </div>
    </div>

    <div class="mb-10">
      <h2 class="mb-3">Languages</h2>
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <% @skills[0].languages.each do |language| %>
          <div class="p-2 flex justify-center items-center w-full h-20 border-solid border-2 border-gray-800 rounded-lg hover:border-indigo-600 hover:border-4"><h3 class="text-lg text-center"><%= language %></h3></div>
        <% end %>
      </div>
    </div>

    <div>
      <h2 class="mb-3">Tools</h2>
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <% @skills[0].tools.each do |tools| %>
          <div class="p-2 flex justify-center items-center w-full h-20 border-solid border-2 border-gray-800 rounded-lg hover:border-indigo-600 hover:border-4"><h3 class="text-lg text-center"><%= tools %></h3></div>
        <% end %>
      </div>
    </div>

  </div>

  <div class="mb-40">

    <div class="mb-14">
      <h1 class="mb-5">Product Design</h1>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <% @skills[1].topics.each do |topic| %>
          <div class="p-2 flex justify-center items-center w-full h-20 border-solid border-2 border-gray-800 rounded-lg hover:border-indigo-600 hover:border-4"><h3 class="text-lg text-center"><%= topic %></h3></div>
        <% end %>
      </div>
    </div>

    <h2 class="mb-3">Tools</h2>
    <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
      <% @skills[1].tools.each do |tools| %>
        <div class="p-2 flex justify-center items-center w-full h-20 border-solid border-2 border-gray-800 rounded-lg hover:border-indigo-600 hover:border-4"><h3 class="text-lg text-center"><%= tools %></h3></div>
      <% end %>
    </div>

  </div>

</div>